fragment AuthenticatedUser on User {
  id
  email
  createdAt
  updatedAt
}

fragment Tokens on Credential {
  tokenKind
  accessToken
  refreshToken
}

fragment Auth on Authenticated {
  user {
    ...AuthenticatedUser
  }
  credential {
    ...Tokens
  }
}
