#!/usr/bin/env bash

if  [ "$NODE_ENV" = "production" ]; then
    echo $PRODUCTION_ENV | tr ";" "\n" > .env.production
elif [ "$NODE_ENV" = "development" ]; then
    echo $DEVELOPMENT_ENV | tr ";" "\n" > .env.development
elif [ "$NODE_ENV" = "preview" ]; then
    echo $PREVIEW_ENV | tr ";" "\n" > .env.preview
fi
