query Accounts {
  accounts {
    edges {
      cursor
      node {
        ...Account
        transactions {
          edges {
            cursor
            node {
              ...Transaction
            }
          }
        }
      }
    }
  }
}
