fragment AuthenticatedUser on User {
  id
  email
  createdAt
  updatedAt
}
fragment Tokens on Credential {
  tokenType
  accessToken
  refreshToken
}

fragment Auth on Authenticated {
  user {
    ...AuthenticatedUser
  }
  credentials {
    ...Tokens
  }
}

query Me {
  me {
    ...AuthenticatedUser
  }
}

mutation Login($input: AuthInput!) {
  login(input: $input) {
    ...Auth
  }
}

mutation Register($input: AuthInput!) {
  register(input: $input) {
    ...Auth
  }
}

mutation RefreshToken($token: String!) {
  refreshToken(token: $token) {
    ...Tokens
  }
}
