name: Build iOS

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/build-ios.yml"
      - "ios/**"
      - "yarn.lock"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"

      - name: Install node dependencies
        run: yarn

      - name: Install pods
        working-directory: ios
        run: pod install
        env:
          APP_ENV: development

      - name: Build app
        run: yarn ios --scheme ownda-dev

      - name: Commit automatic changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci(podfile): apply automatic changes"
          file_pattern: ios/Podfile**
          commit_options: '--no-verify'

