name: Build Android

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/build-android.yml"
      - "android/**"
      - "yarn.lock"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"

      - name: Install node dependencies
        run: yarn

      - name: Build app
        working-directory: android
        run: ./gradlew assembleDevelopmentDebug --no-daemon --console=plain
